### ISSUE TITLE
Missing `messages` definition in example code

### ISSUE THREAD

**Issue by ngc-shj** [Hajime-Y/reasoning-model#1]
Thank you for creating and sharing this excellent QwQ-CoT model!

In the example code for using the model, there is a small oversight where `messages` is used but not defined, which causes an error when running the code:

```python
# chat_templateとtokenize
text = tokenizer.apply_chat_template(
    messages,  # <-- messages is undefined
    tokenize=False,
    add_generation_prompt=True
)
```
Suggested fix:
Add the following code before the tokenizer application:
```python
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user", "content": prompt}
]
```

**Comment by Hajime-Y** [comment]
Thank you for your feedback and the detailed suggestion! You're absolutely right about the undefined messages variable. I'll fix this right away.

**Comment by Hajime-Y** [comment]
I've fixed the example code in the README. Thank you again for reporting this issue!
